name: midoc
description: A new Flutter project.
publish_to: 'none'
version: 0.1.0

environment:
  sdk: '>=2.10.5 '

dependencies:
  window_manager: ^0.2.5
  flutter_bloc: ^8.1.3
  bloc: ^8.1.2
  mongo_dart: ^0.5.0-beta 
  provider: ^6.0.5
  flutter:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^1.0.4

flutter:
  uses-material-design: true
